name: chikitsak
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^0.1.3
  tabbar:
  email_validator:
  flushbar:
  step_progress_indicator:
  floating_bottom_navigation_bar:
  shared_preferences: ^0.5.10
  firebase_core:
  firebase_auth:
  cloud_firestore:
  smooth_page_indicator:
  google_sign_in:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true

  assets:
    - assets/

  
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Black.ttf
        - asset: fonts/Montserrat-BlackItalic.ttf
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat-ExtraLight.ttf
        - asset: fonts/Montserrat-ExtraLightItalic.ttf
        - asset: fonts/Montserrat-Italic.ttf
        - asset: fonts/Montserrat-Light.ttf
        - asset: fonts/Montserrat-LightItalic.ttf
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-MediumItalic.ttf
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-semiBold.ttf
        - asset: fonts/Montserrat-semiBoldItalic.ttf
        - asset: fonts/Montserrat-Thin.ttf
        - asset: fonts/Montserrat-ThinItalic.ttf

